import type { ReactNode } from "react";
import { AlertCircle, CheckCircle2, Inbox, Loader2 } from "lucide-react";
import { cn } from "@/lib/cn";
export function EmptyState({ title, description, action, className }: { title: string; description?: string; action?: ReactNode; className?: string }) { return <div className={cn("flex min-h-48 flex-col items-center justify-center rounded-xl border border-dashed border-hairline-strong bg-surface/40 px-6 py-10 text-center", className)}><Inbox size={22} className="mb-3 text-ink-faint" /><h3 className="text-[14px] font-medium text-ink">{title}</h3>{description && <p className="mt-1 max-w-md text-[12.5px] leading-5 text-ink-muted">{description}</p>}{action && <div className="mt-4">{action}</div>}</div>; }
export function LoadingState({ label = "Memuat data...", className }: { label?: string; className?: string }) { return <div className={cn("flex min-h-32 items-center justify-center gap-2 text-[12.5px] text-ink-muted", className)}><Loader2 size={16} className="animate-spin" />{label}</div>; }
export function ErrorState({ title = "Data belum dapat dimuat", description = "Coba lagi.", action, className }: { title?: string; description?: string; action?: ReactNode; className?: string }) { return <div className={cn("rounded-xl border border-status-blocked/20 bg-status-blocked/5 p-4", className)}><div className="flex gap-3"><AlertCircle size={17} className="mt-0.5 shrink-0 text-status-blocked" /><div><p className="text-[13px] font-medium text-ink">{title}</p><p className="mt-0.5 text-[12px] text-ink-muted">{description}</p>{action && <div className="mt-3">{action}</div>}</div></div></div>; }
export function SuccessState({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn("flex items-center gap-2 rounded-lg border border-status-ready/20 bg-status-ready/5 px-3 py-2.5 text-[12.5px] text-ink", className)}><CheckCircle2 size={16} className="text-status-ready" />{children}</div>; }
export function Skeleton({ className }: { className?: string }) { return <div aria-hidden className={cn("animate-pulse rounded-md bg-surface-elevated", className)} />; }
export function TableSkeleton({ rows = 5, columns = 4 }: { rows?: number; columns?: number }) { return <div className="space-y-px overflow-hidden rounded-xl border border-hairline">{Array.from({length: rows}).map((_, r) => <div key={r} className="flex h-11 items-center gap-4 border-b border-hairline px-4 last:border-0">{Array.from({length: columns}).map((_, c) => <Skeleton key={c} className={cn("h-3 flex-1", c === 0 && "max-w-28")} />)}</div>)}</div>; }
